# Generated by Django 4.1 on 2024-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strip_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
